layout_spectrum: 0
color:
  saturation: 0
  brandStrength: 0.9304934
  lightness: 0
  rhythmicContrast: 0
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.1186896
name: Interior Photography
